AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/*.rb"
    - "bin/*"
    - "config/application.rb"
    - "config/initializers/*.rb"
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 18
